name: Pipeline
run-name: ${{ github.event.head_commit.message }}
on: [push]

jobs:
  Pipeline:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Setup Serverless
        run: |
          npm i -g serverless@4
          npm i -g @serverless/compose
      - name: Build client
        run: |
          cd client 
          npm ci --silent
          npm run build
      - name: Build API
        run: |
          cd api
          make build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Serverless Deploy
        run: serverless deploy --stage main --verbose
